---
title: "Metodo de R2 ajustado"
output: html_notebook
---


Necessary libraries

```{r}

library(MASS)
library(lmtest)
library(nortest)
library(crayon)

```

DataFrame

```{r}

babies<-read.csv("C:/Users/yosef/OneDrive/Documents/Esp_Estadistica/Applied-regression-methods-/Correlation/Examples/babies.csv", header=T,sep=";")
babies
attach(babies)

```

Dimensiones del Dataframe 

```{r}

dim(babies)

```

Dataframe summary

```{r}

summary(babies)

```


Datos del R2 del dataframe


```{r}



#SLR
pesoNacer <- summary(lm(Talla_hoy ~ Peso_nacer))
pesoNacer_c<- cbind(pesoNacer$r.squared, pesoNacer$adj.r.squared)

tallaNacer <- summary(lm(Talla_hoy ~ Talla_nacer))
tallaNacer_c <- cbind(tallaNacer$r.squared, tallaNacer$adj.r.squared)

toraxNacer <- summary(lm(Talla_hoy ~ Torax_nacer))
toraxNacer_c <- cbind(toraxNacer$r.squared, toraxNacer$adj.r.squared)



#MLR

pesoTallaNacer <- summary(lm(Talla_hoy ~ Peso_nacer + Talla_nacer))
pesoTallaNacer_c <- cbind(pesoTallaNacer$r.squared, pesoTallaNacer$adj.r.squared)

pesoToraxNacer <- summary(lm(Talla_hoy ~ Peso_nacer + Torax_nacer))
pesoToraxNacer_c <- cbind(pesoToraxNacer$r.squared, pesoToraxNacer$adj.r.squared)

tallaToraxNacer <- summary(lm(Talla_hoy ~ Talla_nacer + Torax_nacer))
tallaToraxNacer_c <- cbind(tallaToraxNacer$r.squared, tallaToraxNacer$adj.r.squared)

pesoTallaToraxNacer <- summary(lm(Talla_hoy ~ Peso_nacer + Talla_nacer + Torax_nacer))
pesoTallaToraxNacer_c <- cbind(pesoTallaToraxNacer$r.squared, pesoTallaToraxNacer$adj.r.squared)


```

#### Tabla R2

```{r}

tablaR2 <- rbind(pesoNacer_c, tallaNacer_c ,toraxNacer_c, pesoTallaNacer_c, pesoToraxNacer_c, tallaToraxNacer_c, pesoTallaToraxNacer_c )

colnames(tablaR2) <- c("R2   ", "R2 ajustado")
rownames(tablaR2) <- c("pesoNacer", "tallNacer", "toraxNacer", "pesoTallaNacer", "pesoToraxNacer", "tallToraxNacer", "pesoTallaToraxNacer"  )

tablaR2 <- round(tablaR2,2)
tablaR2
```


