---
title: "R Notebook"
output: html_notebook
---



```{r}
library(MASS)
require(zoo)
library(lmtest)
library(nortest)
```

```{r}
data(mtcars)
head(mtcars)
attach(mtcars)
```


```{r}
full.model <- lm(mpg ~ disp + hp + wt)
AIC <- step(full.model)
```

```{r}

mpg.hp.wt <- lm(mpg ~ hp + wt)

```


```{r}
### Funcion de validacion de supuestos
ValidarSupuestos <- function (respuesta ,modelo,confianza){
  
  # Test de normalidad
  
  shapiro <- shapiro.test(modelo$residuals)
  shapiro <- shapiro$p.value
  
  lillie <- lillie.test(modelo$residuals)
  lillie <- lillie$p.value
  
    ifelse((shapiro > confianza) & (lillie > confianza), print("Existe normalidad de los errores"), print("No existe normalidad de los errores"))
  
  # Test de homocedasticidad
  
  
  baruch <- bptest(modelo)
  baruch <- baruch$p.value

  golfred <- gqtest(modelo)
  golfred <- golfred$p.value

  ifelse((baruch > confianza) & (golfred > confianza), print("Existe homocedasticidad"), print("No existe homocedasticidad"))
  
  # Test de independencia
  
  indepenencia <- dwtest(respuesta ~ modelo$residuals)
  indepenencia <- indepenencia$p.value
  
  ifelse((indepenencia > confianza), print("Hay independencia"), print("No hay independencia"))
  
  # Construccion de la Tabla de respuestas
  
  tabla <- rbind(shapiro, lillie, baruch, golfred, indepenencia)
  rownames(tabla) <- c("shapiro", "lillie", "baruch", "golfred", "independencia")
  colnames(tabla) <- c("p.value")
  
  print(round(tabla,5))

  
} 
```


```{r}

# validarSupuestos(respuesta, modelo, confianza)
ValidarSupuestos(mpg,mpg.hp.wt,0.05)
```

```{r}

log.mpg <- log(mpg)

log.mpg.hp.wt <- lm(log.mpg ~ hp + wt)
ValidarSupuestos(log.mpg,log.mpg.hp.wt,0.05)

```

```{r}

log.10.mpg <- log(mpg)

log.10.mpg.hp.wt <- lm(log.10.mpg ~ hp + wt)
ValidarSupuestos(log.10.mpg,log.10.mpg.hp.wt,0.05)

```

```{r}

sqrt.mpg <- sqrt(mpg)

sqrt.mpg.hp.wt <- lm(sqrt.mpg ~ hp + wt)
ValidarSupuestos(sqrt.mpg,sqrt.mpg.hp.wt,0.05)

```