---
title: "R Notebook"
output: html_notebook
---

```{r}
library(MASS)
require(zoo)
library(lmtest)
library(nortest)
```

```{r}
stateed <- read.csv("stateed.csv", header = T, sep=";")
head(stateed)
attach(stateed)
```

```{r}
### Funcion de validacion de supuestos
ValidarSupuestos <- function (respuesta ,modelo,alpha){
  
  # Test de normalidad
  
  shapiro <- shapiro.test(modelo$residuals)
  shapiro <- shapiro$p.value
  
  lillie <- lillie.test(modelo$residuals)
  lillie <- lillie$p.value
  
    ifelse((shapiro > alpha) & (lillie > alpha), print("Existe normalidad de los errores"), print("No existe normalidad de los errores"))
  
  # Test de homocedasticidad
  
  
  baruch <- bptest(modelo)
  baruch <- baruch$p.value

  golfred <- gqtest(modelo)
  golfred <- golfred$p.value

  ifelse((baruch > alpha) & (golfred > alpha), print("Existe homocedasticidad"), print("No existe homocedasticidad"))
  
  # Test de independencia
  
  indepenencia <- dwtest(respuesta ~ modelo$residuals)
  indepenencia <- indepenencia$p.value
  
  ifelse((indepenencia > alpha), print("Hay independencia"), print("No hay independencia"))
  
  # Construccion de la Tabla de respuestas
  
  tabla <- rbind(shapiro, lillie, baruch, golfred, indepenencia)
  rownames(tabla) <- c("shapiro", "lillie", "baruch", "golfred", "independencia")
  colnames(tabla) <- c("p.value")
  
  print(round(tabla,5))
  
} 
```


```{r}

modelo <- lm(STATEAID ~ ELDERLY)

ValidarSupuestos(STATEAID, modelo, 0.05)
```

```{r}
# Intervalio de alpha al 90% con x = mean(x)

w_new = 3549.25 -100.84 * mean(ELDERLY)
w_new
```
```{r}
CME = anova(modelo)[2,3]
CME
```
```{r}

# Intervalo de predicción del 90% para w
n <- nrow(stateed)
Inferior.w<- w_new - qt(0.95,n-2) *sqrt(CME*(1+(1/n)))
Superior.w<- w_new + qt(0.95,n-2) *sqrt(CME*(1+(1/n)))
Intervalo.para.w <- cbind(Inferior.w, Superior.w)
Intervalo.para.w

```

```{r}
summary(STATEAID)
```

