---
title: "R Notebook"
output: html_notebook
---

```{r}
library(MASS)
require(zoo)
library(lmtest)
library(nortest)
```

```{r}
data(swiss)
head(swiss)
attach(swiss)
```

```{r}
### Funcion de validacion de supuestos
ValidarSupuestos <- function (respuesta ,modelo,alpha){
  
  # Test de normalidad
  
  shapiro <- shapiro.test(modelo$residuals)
  shapiro <- shapiro$p.value
  
  lillie <- lillie.test(modelo$residuals)
  lillie <- lillie$p.value
  
    ifelse((shapiro > alpha) & (lillie > alpha), print("Existe normalidad de los errores"), print("No existe normalidad de los errores"))
  
  # Test de homocedasticidad
  
  
  baruch <- bptest(modelo)
  baruch <- baruch$p.value

  golfred <- gqtest(modelo)
  golfred <- golfred$p.value

  ifelse((baruch > alpha) & (golfred > alpha), print("Existe homocedasticidad"), print("No existe homocedasticidad"))
  
  # Test de independencia
  
  indepenencia <- dwtest(respuesta ~ modelo$residuals)
  indepenencia <- indepenencia$p.value
  
  ifelse((indepenencia > alpha), print("Hay independencia"), print("No hay independencia"))
  
  # Construccion de la Tabla de respuestas
  
  tabla <- rbind(shapiro, lillie, baruch, golfred, indepenencia)
  rownames(tabla) <- c("shapiro", "lillie", "baruch", "golfred", "independencia")
  colnames(tabla) <- c("p.value")
  
  print(round(tabla,5))
  
} 
```

```{r}

modelo <- lm(Fertility ~ Agriculture + Examination + Education + Catholic + Infant.Mortality)

AIC <- step(modelo)

```


```{r}
modelo <- lm(Fertility ~ Agriculture + Education)

ValidarSupuestos(Fertility, modelo , 0.05)
```

Press ultimo resudual
```{r}
y_sin <- swiss[-47,]
y_i <- swiss[47,]

modelo_sin <- lm(Fertility ~ Agriculture + Education, data= y_sin)

y_i_hat <- predict(modelo_sin, y_i)

residual_press <- y_i$Fertility - y_i_hat
residual_press
```

